name: Build Android APK

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Node 环境并缓存 pnpm
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install pnpm
        run: npm install -g pnpm

      - name: install dependencies
        run: pnpm install

      # 2. 设置 Rust 环境 (添加安卓交叉编译目标)
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android, i686-linux-android

      # 3. 开启 Rust 编译缓存，避免每次都重排
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"

      # 4. 设置 Java 和 Android SDK
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup android sdk
        uses: android-actions/setup-android@v3

      # 5. 编译 APK (Debug 版本)
      # 如果你以后要 Release，需要配置签名，这里先用 --debug 跑通流程
      - name: build android
        run: pnpm tauri android build --debug

      # 6. 归档 APK
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iTermX-Debug-APK
          path: src-tauri/gen/android/app/build/outputs/apk/debug/*.apk
